language: python
python: '2.7'
env:
  global:
  - GITLAB_API_URL=https://gitlab.com/api/v4

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python-pycurl

install:
- pip install ansible ansible-lint
- ansible --version

script:
- ansible-lint tasks/*.yml
- |
  ANSIBLE_ROLES_PATH=$(pwd)/.. ansible-playbook \
    -i tests/hostfile \
    -e "role_name=ansible-gitlab-config" \
    -e "gitlab_api_url=$GITLAB_API_URL" \
    -e "gitlab_token=$GITLAB_TOKEN" \
    tests/gitlab-config.yml --syntax-check
- |
  ANSIBLE_ROLES_PATH=$(pwd)/.. ansible-playbook \
    -i tests/hostfile \
    -e "role_name=ansible-gitlab-config" \
    -e "gitlab_api_url=$GITLAB_API_URL" \
    -e "gitlab_token=$GITLAB_TOKEN" \
    tests/gitlab-config.yml --list-tasks

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
