---
- name: "Delete project {{ name }}"
  uri:
    url: "{{ gitlab_api_url }}/projects/{{ path_name }}"
    method: DELETE
    body_format: json
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code: 202,404
#    body: "{{ json | to_json }}"
    validate_certs: "no"
  changed_when: true
  register: gitlab_delete_project
