---
- name: "Delete group {{ name }}"
  uri:
    url: "{{ gitlab_api_url }}/groups/{{ group_id }}"
    method: DELETE
    body_format: json
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code: 204,404
    body: "{{ json | to_json }}"
    validate_certs: "no"
  changed_when: true
  register: gitlab_delete_group
