---
- name: "Get current settings for project {{ name }}"
  uri:
    url: '{{ gitlab_api_url }}/projects/{{ path_name }}'
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code: 200,404
    validate_certs: "no"
  register: gitlab_projects_request
