---
- name: "Check Gitlab host"
  fail:
    msg: "missing required variable 'gitlab_host'"
  when: ( gitlab_host is not defined ) or ( gitlab_host is none ) or ( gitlab_host | trim =="" )

- name: "Check Gitlab auth token or user/password"
  fail:
    msg: "missing required variable: ( 'gitlab_token' ) or ( 'gitlab_user' 'gitlab_password' )"
  when: ( ( gitlab_token is not defined ) or ( gitlab_token is none )  or ( gitlab_token | trim =="" ) )
        and (
            ( ( gitlab_user is not defined ) or ( gitlab_user is none )  or ( gitlab_user | trim =="" ) )
        or ( ( gitlab_password is not defined ) or ( gitlab_password is none )  or ( gitlab_password | trim =="" ) )
        )

- name: "Get Gitlab token"
  include: "get_token.yaml"
  when: ( gitlab_token is not defined ) or ( gitlab_token is none )  or ( gitlab_token | trim =="" )

# Manage Gitlab setting
- name: "Get Gitlab version"
  include: "version.yaml"
  when: ( gitlab_api_url is defined and gitlab_api_url )
        and ( gitlab_token is defined and gitlab_token )

- name: "Check Gitlab version"
  fail:
    msg: "gitlab version 'gitlab_version' not detected"
  when: ( gitlab_version is not defined ) or ( gitlab_version is none )  or ( gitlab_version | trim =="" )

# Manage Gitlab setting
- name: "Manage Gitlab application settings"
  include: "application_settings.yaml"
  when: ( gitlab_application_settings is defined and gitlab_application_settings )

# Manage Gitlab users
- name: "Manage Gitlab local users"
  include: setup_user_each.yml
  with_items: "{{ gitlab_local_users }}"
  when: ( gitlab_api_url is defined and gitlab_api_url )

# Manage Gitlab groups
- name: "Manage Gitlab local groups"
  include: setup_group_each.yml
  with_items: "{{ gitlab_groups }}"
  when: ( gitlab_groups is defined and gitlab_groups )

# Manage Gitlab projects
- name: "Manage Gitlab local projects"
  include: setup_project_each.yml
  with_items: "{{ gitlab_projects }}"
  when: ( gitlab_projects is defined and gitlab_projects )
