---
# Manage Gitlab projects
#
# `gitlab_projects` is a list of the form
#    - name: value
#      path: value
#      description: value
#
# Dirty: urlencode does not encode slash
- set_fact:
    path_with_namespace: '{{ item.path }}'
    pattern: '\/'
    replace: "%2F"

- set_fact:
    path_with_namespace: '{{ item.namespace + "/" + item.path }}'
  when: ( item.namespace is defined ) and ( item.namespace )

- set_fact:
    path_with_namespace_urlencoded: "{{ path_with_namespace | regex_replace(pattern, replace ) }}"

# get
- include: get_project.yml
  vars:
    name: "{{ path_with_namespace }}"
    path_name: "{{ path_with_namespace_urlencoded }}"
    json: "{{ item }}"

- set_fact:
    current_project: ""

- set_fact:
    current_project: "{{ gitlab_projects_request.json }}"
  when: ( gitlab_projects_request.json is defined ) and ( gitlab_projects_request.json | length > 1)
        and ( gitlab_projects_request.status == 200 )

- include: get_namespace.yml
  vars:
    name: "{{ item.namespace }}"
    json: "{{ item }}"

- set_fact:
    current_namespace: ""

- set_fact:
    current_namespace: "{{ gitlab_namespaces_request.json }}"
  when: ( gitlab_namespaces_request.json is defined ) and ( gitlab_namespaces_request.json )
        and ( gitlab_namespaces_request.status == 200 )

# delete
- include: delete_project.yml
  vars:
    name: "{{ path_with_namespace }}"
    path_name: "{{ path_with_namespace_urlencoded }}"
    project_id: "{{ current_project.id }}"
    json: "{{ item }}"
  when: ( current_project.id is defined )
        and ( item.delete is defined ) and ( item.delete | bool )

#- name: "DEBUGG "
#  debug:
#    msg: >
#      {{ item.name }}
#      {{ item.path }}
#      {{ item.namespace }}
#      {{ path_with_namespace }}
#      {{ current_project.id | default ('none') }}
#      {{ current_namespace.id | default ('none') }}

# create
- include: create_project.yml
  vars:
    name: "{{ item.name }}"
    namespace: "{{ current_namespace }}"
    json: "{{ item }}"
  when: ( current_project.id is not defined )
       and ( current_namespace.id is defined )
       and ( ( item.delete is not defined ) or ( item.delete is defined and not ( item.delete | bool ) ) )

# update
- include: update_project.yml
  vars:
    name: "{{ item.name }}"
    path_name: "{{ path_with_namespace_urlencoded }}"
    project_id: "{{ current_project.id }}"
    json: "{{ item }}"
  when: ( current_project.id is defined )
       and ( current_namespace.id is defined )
       and ( ( item.delete is not defined ) or ( ( item.delete is defined ) and not ( item.delete | bool ) ) )
        and ( gitlab_update_projects is defined ) and ( gitlab_update_projects | bool )
#
# Add members
#
# get
- include: get_project.yml
  vars:
    name: "{{ path_with_namespace }}"
    path_name: "{{ path_with_namespace_urlencoded }}"
    json: "{{ item }}"

- set_fact:
    current_project: ""

- set_fact:
    current_project: "{{ gitlab_projects_request.json }}"
  when: ( gitlab_projects_request.json is defined ) and ( gitlab_projects_request.json | length > 1)
        and ( gitlab_projects_request.status == 200 )

- include: get_namespace.yml
  vars:
    name: "{{ item.namespace }}"
    json: "{{ item }}"

- set_fact:
    current_namespace: ""

- set_fact:
    current_namespace: "{{ gitlab_namespaces_request.json }}"
  when: ( gitlab_namespaces_request.json is defined ) and ( gitlab_namespaces_request.json )
        and ( gitlab_namespaces_request.status == 200 )

- include: setup_member_each.yml
  vars:
    name: "{{ item.name }}"
    group_id: "{{ current_project.id }}"
    member: "{{ member_item }}"
    _kind: "projects"
  with_items: "{{ item.members }}"
  loop_control:
    loop_var: member_item
  when: ( current_project.id is defined )
       and ( ( item.delete is not defined ) or ( ( item.delete is defined ) and not ( item.delete | bool ) ) )
       and ( gitlab_update_projects is defined ) and ( gitlab_update_projects | bool )
