---
- name: "Update user {{ username }}"
  uri:
    url: "{{ gitlab_api_url }}/users/{{ user_id }}"
    method: PUT
    body_format: json
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code: 200
    body: "{{ json | to_json }}"
    validate_certs: "no"
  changed_when: true
  register: gitlab_update_user
