---
# https://docs.gitlab.com/ce/api/projects.html#project-modification
- set_fact:
    body: >
      {{ lookup('template', 'update_project.json.j2', convert_data=False ) }}

- debug: var=body

- name: "Update project {{ name }}"
  uri:
    url: "{{ gitlab_api_url }}/projects/{{ project_id }}"
    method: PUT
    headers:
      Content-Type: application/json
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code: 200
    body_format: json
    body: '{{ body }}'
    validate_certs: "no"
  changed_when: true
  register: gitlab_update_project

- debug: var=gitlab_update_project.json
